### ISSUE TITLE
Error: Missing field `nGpuLayers`

### ISSUE THREAD

**Issue by m0dE** [withcatai/catai#17]
I'm trying to run Wizard-Vicuna-13B-Uncensored model on a VM (16GB RAM), but i'm getting the below error:

Error: Missing field `nGpuLayers`
    at LLamaCpp.<anonymous> (file:///usr/local/lib/node_modules/catai/node_modules/llama-node/dist/llm/llama-cpp.js:63:35)
    at Generator.next (<anonymous>)
    at file:///usr/local/lib/node_modules/catai/node_modules/llama-node/dist/llm/llama-cpp.js:33:61
    at new Promise (<anonymous>)
    at __async (file:///usr/local/lib/node_modules/catai/node_modules/llama-node/dist/llm/llama-cpp.js:17:10)
    at LLamaCpp.load (file:///usr/local/lib/node_modules/catai/node_modules/llama-node/dist/llm/llama-cpp.js:61:12)
    at LLM.load (/usr/local/lib/node_modules/catai/node_modules/llama-node/dist/index.cjs:52:21)
    at #addNew (file:///usr/local/lib/node_modules/catai/src/alpaca-client/node-llama/process-pull.js:88:21)
    at new NodeLlamaActivePull (file:///usr/local/lib/node_modules/catai/src/alpaca-client/node-llama/process-pull.js:19:38)
    at file:///usr/local/lib/node_modules/catai/src/alpaca-client/node-llama/node-llama.js:8:48 {
  code: 'InvalidArg'
}

**Comment by celisum** [comment]
+1

**Comment by ido-pluto** [comment]
Currently checking this

**Comment by ido-pluto** [comment]
Fix in the lastest version, use `catai update` to upgrade
