### ISSUE TITLE
Error: The connection lost, check the server status and refresh the page.

### ISSUE THREAD

**Issue by Gasiorrr** [withcatai/catai#49]
Describe the bug
Error: The connection lost, check the server status and refresh the page.

**Screenshots**

C:\Windows\System32>catai up
CatAI client on http://127.0.0.1:3000
New connection
Failed to load prebuilt binary for platform "win32" "x64". Error: Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\ppodl\AppData\Roaming\npm\node_modules\catai\node_modules\node-llama-cpp\llamaBins\win-x64\llama-addon.node    at Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at loadBin (file:///C:/Users/ppodl/AppData/Roaming/npm/node_modules/catai/node_modules/node-llama-cpp/dist/utils/getBin.js:45:24)
    at async file:///C:/Users/ppodl/AppData/Roaming/npm/node_modules/catai/node_modules/node-llama-cpp/dist/llamaEvaluator/LlamaBins.js:2:29 {
  code: 'ERR_DLOPEN_FAILED'
}
Falling back to locally built binaries
file:///C:/Users/ppodl/AppData/Roaming/npm/node_modules/catai/node_modules/node-llama-cpp/dist/utils/compileLLamaCpp.js:93
    throw new Error("Could not find Release or Debug directory");
          ^

Error: Could not find Release or Debug directory
    at getCompiledResultDir (file:///C:/Users/ppodl/AppData/Roaming/npm/node_modules/catai/node_modules/node-llama-cpp/dist/utils/compileLLamaCpp.js:93:11)
    at async getCompiledLlamaCppBinaryPath (file:///C:/Users/ppodl/AppData/Roaming/npm/node_modules/catai/node_modules/node-llama-cpp/dist/utils/compileLLamaCpp.js:80:35)
    at async loadBin (file:///C:/Users/ppodl/AppData/Roaming/npm/node_modules/catai/node_modules/node-llama-cpp/dist/utils/getBin.js:57:24)
    at async file:///C:/Users/ppodl/AppData/Roaming/npm/node_modules/catai/node_modules/node-llama-cpp/dist/llamaEvaluator/LlamaBins.js:2:29

Node.js v20.8.0

**Comment by Gasiorrr** [comment]
Node.js v18.18.0 still the same problem

**Comment by ido-pluto** [comment]
I will check that, seems like the similar bug to #48

**Comment by Gasiorrr** [comment]
do you get what i should to fix?

**Comment by ido-pluto** [comment]
This is a problem with one of the CatAI package node-llama-cpp, A fix is on the way :) . If you want a quick fix, you can cd to node-llama-cpp dep and run 

```
npx node-llama-cpp download
```

This will recompile the node addon and hopefully work

**Comment by Gasiorrr** [comment]
Still the same problem

**Comment by ido-pluto** [comment]
A new version of node-llama-cpp has been released.
Please update with `catai update` and try again.

Is this issue solved?

**Comment by Gasiorrr** [comment]
Error: Command npm run -s cmake-js-llama -- clean --log-level warn exited
with code 1
    at ChildProcess.<anonymous>
(file:///C:/Windows/System32/node_modules/node-llama-cpp/dist/utils/spawnCommand.js:27:24)
    at ChildProcess.emit (node:events:517:28)
    at cp.emit
(C:\Windows\System32\node_modules\cross-spawn\lib\enoent.js:34:29)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)

**Comment by ido-pluto** [comment]
Checking that :)

**Comment by ido-pluto** [comment]
Are you running on x86 right?

**Comment by Gasiorrr** [comment]
No, I am not. I'm on 64 os windows 11

**Comment by Gasiorrr** [comment]
the update fix the problem thanks a lot!
