### ISSUE TITLE
Model Not Found

### ISSUE THREAD

**Issue by sam1am** [withcatai/catai#6]
After Installing a model and running catai serve I get this error: 

```
catai use 30B
$ cd /usr/lib/node_modules/catai
$ npm run use 30B

> catai@0.3.0 use
> zx scripts/use.js 30B

Model set to 30B
user@Machine:~/FastChat$ catai serve --ui chatGPT
$ cd /usr/lib/node_modules/catai
$ npm start production chatGPT

> catai@0.3.0 start
> node src/index.js production chatGPT

llama.cpp: loading model from /home/user/catai/models/30B
llama_model_load_internal: format     = 'ggml' (old version with low tokenizer quality and no mmap support)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 1024
llama_model_load_internal: n_embd     = 6656
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 52
llama_model_load_internal: n_layer    = 60
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 17920
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 30B
llama_model_load_internal: ggml ctx size = 19856856.30 KB
llama_model_load_internal: mem required  = 21695.46 MB (+ 6248.00 MB per state)
....................................................................................................
llama_init_from_file: kv self size  = 3120.00 MB
file:///usr/lib/node_modules/catai/src/chat.js:7
    throw new Error('Model not found, try re-downloading the model');
          ^

Error: Model not found, try re-downloading the model
    at file:///usr/lib/node_modules/catai/src/chat.js:7:11

Node.js v20.0.0
llama.cpp: loading model from /home/user/catai/models/30B
llama_model_load_internal: format     = 'ggml' (old version with low tokenizer quality and no mmap support)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 1024
llama_model_load_internal: n_embd     = 6656
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 52
llama_model_load_internal: n_layer    = 60
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 17920
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 30B
llama_model_load_internal: ggml ctx size = 19856856.30 KB
llama_model_load_internal: mem required  = 21695.46 MB (+ 6248.00 MB per state)
....................................................................................................
llama_init_from_file: kv self size  = 3120.00 MB
file:///usr/lib/node_modules/catai/src/chat.js:7
    throw new Error('Model not found, try re-downloading the model');
          ^

Error: Model not found, try re-downloading the model
    at file:///usr/lib/node_modules/catai/src/chat.js:7:11

Node.js v20.0.0
    at file:///usr/lib/node_modules/catai/scripts/cli.js:55:27
    exit code: 1
```

Strange, as it appears to find and load the model, then afterwards complain that it's not found. 

This happens with the &B model as well, though I am currently having trouble re-installing it.

**Comment by sam1am** [comment]
I should note I also tried the solution in the Readme. 

`export const SELECTED_BINDING = 'alpaca-cpp';`

This produced the same result.

**Comment by ido-pluto** [comment]
Can you attach the content of the file in `~/catai/settings.json`

This error is thrown when some of the files are not indexed in the `settings.json`

**Comment by ido-pluto** [comment]
Please try with the new version - this error should happen only if you have unsupported hardware for `alpaca-cpp` and the selected binding is `alpaca-cpp`
